/**
 * Driver pasted directly into Streamlabs' own Alert Box "Custom HTML/CSS/JS"
 * editor (one type/tier combination at a time, generated by control.html's
 * "Streamlabs Alert Box code" section). Streamlabs handles receiving the
 * Twitch event, queueing alerts, and controlling how long each stays on
 * screen; this file only has to render one event, once, using whatever
 * `{token}` values Streamlabs substituted into the pasted HTML before this
 * page loaded.
 *
 * Tier and layout variant aren't computed here: control.html bakes a fixed
 * `data-tier`/`data-variant` into each generated widget, so pasting, say,
 * the "Tip / Huge / Jar" output into its own Streamlabs Alert Box variation
 * and setting that variation's own condition (Streamlabs' own amount-based
 * routing, not anything in this file) is what decides which pasted widget
 * fires for a given event.
 *
 * There's no relay, socket, or token to manage here: Streamlabs re-renders
 * this HTML fresh for every alert and tears it down after, so there's
 * nothing left running between alerts that could need reconnecting.
 */
import { AlertStage } from "./components/AlertStage.js";

const DURATION = 5000;
const TOP_OFFSET = 96;

/**
 * The seven per-type Alert Box boxes Streamlabs exposes; `resub` and
 * `giftsub` both map to this repo's single `sub` `AlertType`.
 */
type StreamlabsAlertBoxType =
  "follow" | "sub" | "resub" | "giftsub" | "bits" | "raid" | "tip";

const fmt = (n: number): string =>
  String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ",");

/**
 * Reads one `[data-token]` span's text inside `#zw-tokens`. Streamlabs
 * leaves a token's literal `{name}`-shaped placeholder in place when it
 * doesn't apply to this alert type or the platform didn't supply a value,
 * so anything still shaped like `{...}` is treated as absent, not as data.
 */
function readToken(name: string): string {
  const el = document.querySelector<HTMLElement>(
    `#zw-tokens [data-token="${name}"]`,
  );
  const text = el?.textContent?.trim() ?? "";
  if (!text || /^\{.*\}$/.test(text)) {
    return "";
  }
  return text;
}

function readAvatar(): string | undefined {
  return readToken("profile_image") || readToken("img") || undefined;
}

function parseAmount(raw: string): number {
  const n = parseFloat(raw.replace(/[^0-9.]/g, ""));
  return isNaN(n) ? 0 : n;
}

function buildEvent(
  boxType: StreamlabsAlertBoxType,
  tier: AlertTier,
): AlertStageEvent {
  const name = readToken("name") || "someone";
  const avatar = readAvatar();
  const message = readToken("userMessage") || readToken("message") || undefined;

  if (boxType === "follow") {
    return { type: "follow", name, avatar, detail: "just followed", tier };
  }
  if (boxType === "sub") {
    return {
      type: "sub",
      name,
      avatar,
      message,
      detail: "Tier 1 · 1 month",
      amount: "1",
      tier,
    };
  }
  if (boxType === "resub") {
    const months = parseAmount(readToken("amount")) || 1;
    return {
      type: "sub",
      name,
      avatar,
      message,
      detail: `Tier 1 · ${months} ${months === 1 ? "month" : "months"}`,
      amount: String(months),
      tier,
    };
  }
  if (boxType === "giftsub") {
    const count = parseAmount(readToken("count")) || 1;
    return {
      type: "sub",
      name,
      avatar,
      detail: `${count} subs gifted`,
      amount: `×${count}`,
      headline: "Gifted",
      tier,
    };
  }
  if (boxType === "bits") {
    const amount = parseAmount(readToken("amount"));
    return {
      type: "bits",
      name,
      avatar,
      message,
      amount: `${fmt(amount)} bits`,
      detail: "cheered",
      tier,
    };
  }
  if (boxType === "raid") {
    const party = parseAmount(readToken("count")) || 1;
    return {
      type: "raid",
      name,
      avatar,
      party,
      detail: `${party} ${party === 1 ? "mate in tow" : "mates in tow"}`,
      amount: String(party),
      headline: "Incoming raid",
      tier,
    };
  }
  const amount = parseAmount(readToken("amount"));
  return {
    type: "tip",
    name,
    avatar,
    message,
    amount: `$${amount}`,
    detail: "chucked in",
    tier,
  };
}

const tokens = document.getElementById("zw-tokens");
const boxType = tokens?.dataset.alertType as StreamlabsAlertBoxType | undefined;
const tier = (tokens?.dataset.tier as AlertTier | undefined) || "big";
const variant = tokens?.dataset.variant || undefined;
const root = document.getElementById("root");
if (boxType && root) {
  const stage = new AlertStage(root, { top: TOP_OFFSET, onDone: () => {} });
  stage.show({ ...buildEvent(boxType, tier), variant }, DURATION);
} else {
  console.error(
    "[zw] streamlabs-alertbox.js: missing #zw-tokens[data-alert-type] or #root",
  );
}
