/**
 * Driver pasted directly into Streamlabs' own Alert Box "Custom HTML/CSS/JS"
 * editor (one alert type at a time, generated by control.html's "Streamlabs
 * Alert Box code" section). Streamlabs handles receiving the Twitch event,
 * queueing alerts, and controlling how long each stays on screen; this file
 * only has to render one event, once, using whatever `{token}` values
 * Streamlabs substituted into the pasted HTML before this page loaded.
 *
 * There's no relay, socket, or token to manage here: Streamlabs re-renders
 * this HTML fresh for every alert and tears it down after, so there's
 * nothing left running between alerts that could need reconnecting.
 */
import { AlertStage } from "./components/AlertStage.js";

const DURATION = 5000;
const TOP_OFFSET = 96;
const TIP_BIG = 20;
const TIP_HUGE = 100;
const BITS_BIG = 1000;
const BITS_HUGE = 5000;
const RAID_BIG = 20;
const RAID_HUGE = 100;
const MONTHS_BIG = 6;
const GIFT_HUGE = 10;

/**
 * The seven per-type Alert Box boxes Streamlabs exposes; `resub` and
 * `giftsub` both map to this repo's single `sub` `AlertType`.
 */
type StreamlabsAlertBoxType =
  "follow" | "sub" | "resub" | "giftsub" | "bits" | "raid" | "tip";

const fmt = (n: number): string =>
  String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ",");

/**
 * Reads one `[data-token]` span's text inside `#zw-tokens`. Streamlabs
 * leaves a token's literal `{name}`-shaped placeholder in place when it
 * doesn't apply to this alert type or the platform didn't supply a value,
 * so anything still shaped like `{...}` is treated as absent, not as data.
 */
function readToken(name: string): string {
  const el = document.querySelector<HTMLElement>(
    `#zw-tokens [data-token="${name}"]`,
  );
  const text = el?.textContent?.trim() ?? "";
  if (!text || /^\{.*\}$/.test(text)) {
    return "";
  }
  return text;
}

function readAvatar(): string | undefined {
  return readToken("profile_image") || readToken("img") || undefined;
}

function parseAmount(raw: string): number {
  const n = parseFloat(raw.replace(/[^0-9.]/g, ""));
  return isNaN(n) ? 0 : n;
}

function buildEvent(boxType: StreamlabsAlertBoxType): AlertStageEvent {
  const name = readToken("name") || "someone";
  const avatar = readAvatar();
  const message = readToken("userMessage") || readToken("message") || undefined;

  if (boxType === "follow") {
    return {
      type: "follow",
      name,
      avatar,
      detail: "just followed",
      tier: "small",
    };
  }
  if (boxType === "sub") {
    return {
      type: "sub",
      name,
      avatar,
      message,
      detail: "Tier 1 · 1 month",
      amount: "1",
      tier: "small",
    };
  }
  if (boxType === "resub") {
    const months = parseAmount(readToken("amount")) || 1;
    return {
      type: "sub",
      name,
      avatar,
      message,
      detail: `Tier 1 · ${months} ${months === 1 ? "month" : "months"}`,
      amount: String(months),
      tier: months >= MONTHS_BIG ? "big" : "small",
    };
  }
  if (boxType === "giftsub") {
    const count = parseAmount(readToken("count")) || 1;
    return {
      type: "sub",
      name,
      avatar,
      detail: `${count} subs gifted`,
      amount: `×${count}`,
      headline: "Gifted",
      tier: count >= GIFT_HUGE ? "huge" : "small",
    };
  }
  if (boxType === "bits") {
    const amount = parseAmount(readToken("amount"));
    return {
      type: "bits",
      name,
      avatar,
      message,
      amount: `${fmt(amount)} bits`,
      detail: "cheered",
      fill: Math.min(1, amount / BITS_HUGE),
      tier: amount >= BITS_HUGE ? "huge" : amount >= BITS_BIG ? "big" : "small",
    };
  }
  if (boxType === "raid") {
    const party = parseAmount(readToken("count")) || 1;
    return {
      type: "raid",
      name,
      avatar,
      party,
      detail: `${party} ${party === 1 ? "mate in tow" : "mates in tow"}`,
      amount: String(party),
      headline: "Incoming raid",
      tier: party >= RAID_HUGE ? "huge" : party >= RAID_BIG ? "big" : "small",
    };
  }
  const amount = parseAmount(readToken("amount"));
  return {
    type: "tip",
    name,
    avatar,
    message,
    amount: `$${amount}`,
    detail: "chucked in",
    tier: amount >= TIP_HUGE ? "huge" : amount >= TIP_BIG ? "big" : "small",
  };
}

const tokens = document.getElementById("zw-tokens");
const boxType = tokens?.dataset.alertType as StreamlabsAlertBoxType | undefined;
const root = document.getElementById("root");
if (boxType && root) {
  const stage = new AlertStage(root, { top: TOP_OFFSET, onDone: () => {} });
  stage.show(buildEvent(boxType), DURATION);
} else {
  console.error(
    "[zw] streamlabs-alertbox.js: missing #zw-tokens[data-alert-type] or #root",
  );
}
