/**
 * Driver pasted directly into Streamlabs' own Alert Box "Custom HTML/CSS/JS"
 * editor, one type/tier/variant combination at a time (generated by
 * control.html's "Streamlabs Alert Box code" section). Streamlabs owns
 * receiving the event and queueing, and re-renders this HTML fresh for
 * every alert, so this file only renders once, from whatever `{token}`
 * values are already substituted into the DOM, with nothing left running
 * afterward that could need reconnecting.
 *
 * Duration is this file's own, not Streamlabs': custom JS has no way to
 * read the streamer's "Alert Duration" setting, only to be torn down when
 * it runs out, so `data-duration` (control.html's Duration field) has to be
 * set to match it by hand, or our own outro can run late and get cut off,
 * or early and leave a blank gap before Streamlabs clears the widget.
 *
 * Tier and variant aren't computed here: each generated widget bakes in a
 * fixed `data-tier`/`data-variant`, and Streamlabs' own per-variation
 * condition (not anything in this file) decides which pasted widget fires.
 */
import { AlertStage } from "./components/AlertStage.js";

const DEFAULT_DURATION_MS = 5000;
const TOP_OFFSET = 96;

// Matches zw-alerts.ts's own default tipHuge threshold: a tip at or above
// this fills the jar's segmented meter completely, same proportional scale
// bits already gets. Tier itself still comes from data-tier, not this.
const TIP_HUGE_THRESHOLD = 100;

// Bumped whenever this file changes materially, so a debug overlay
// screenshot can tell a stale Streamlabs paste apart from a real bug: every
// widget is its own independently-pasted copy (see the file header), so
// "still broken" often just means this specific one wasn't re-copied after
// a fix landed here.
const BUILD_MARKER = "2026-08-21a";

/**
 * The seven per-type Alert Box boxes Streamlabs exposes; `resub` and
 * `giftsub` both map to this repo's single `sub` `AlertType`.
 */
type StreamlabsAlertBoxType =
  "follow" | "sub" | "resub" | "giftsub" | "bits" | "raid" | "tip";

const fmt = (n: number): string =>
  String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ",");

/**
 * Trims raw text and rejects anything still shaped like `{token}`: Streamlabs
 * leaves a token's literal placeholder in place when it doesn't apply to
 * this alert type or the platform didn't supply a value, so that shape
 * means absent, not data.
 */
function cleanText(raw: string | null | undefined): string {
  const text = raw?.trim() ?? "";
  return text && !/^\{.*\}$/.test(text) ? text : "";
}

/**
 * Reads one `[data-token]` span's text from `tokens`' own direct children,
 * stripping non-letters before comparing: Streamlabs has been observed
 * inserting invisible characters into the attribute that break exact
 * matching but look identical in a text dump.
 */
function readToken(tokens: Element, name: string): string {
  const el = Array.from(tokens.children).find(
    (child) =>
      (child as HTMLElement).dataset.token?.replace(/[^a-zA-Z]/g, "") === name,
  ) as HTMLElement | undefined;
  return cleanText(el?.textContent);
}

/**
 * Reads `img`/`messageTemplate`/`userMessage` by the specific element id
 * Streamlabs' own default template uses for each: substitution for these
 * three appears to be keyed off the id itself, not simple text matching,
 * confirmed by removing the id from Streamlabs' own template breaking it.
 */
function readRichText(elementId: string): string {
  return cleanText(document.getElementById(elementId)?.textContent);
}

/**
 * The name Streamlabs substitutes into our own standalone `{name}` token,
 * or, if that's empty, whatever name it embedded inside its own rendered
 * `{messageTemplate}` (it wraps an interpolated `{name}` there in its own
 * `data-token="name"` markup for a letter-reveal animation), which testing
 * has shown to arrive even when the standalone token didn't.
 */
function readName(tokens: Element): string {
  const direct = readToken(tokens, "name");
  if (direct) {
    return direct;
  }
  const alertMessage = document.getElementById("alert-message");
  const nested = alertMessage
    ? Array.from(
        alertMessage.querySelectorAll<HTMLElement>("[data-token]"),
      ).find((el) => el.dataset.token?.replace(/[^a-zA-Z]/g, "") === "name")
    : undefined;
  return cleanText(nested?.textContent);
}

/**
 * A "Send Test Alert" was confirmed (debug overlay screenshot on a real
 * widget) to inject a hidden 1px `<img>` inside `#alert-image` pointing at
 * `streamlabs.com/widgets/frame/alertbox/custom?type=preview`, the widget's
 * own frame URL, not an image, tracking-pixel-style scaffolding unrelated
 * to any `{img}` substitution. Excluded so it's never mistaken for a real
 * uploaded avatar.
 */
function isStreamlabsOwnMarkup(src: string): boolean {
  return /streamlabs\.com\/widgets\//.test(src);
}

/**
 * Reads `#alert-image` defensively: an uploaded Image Gallery pick could
 * arrive as plain text (the original assumption, still tried last) or as an
 * `<img>` Streamlabs substituted in directly or nested inside, since which
 * one it actually uses hasn't been pinned down from a real widget yet. No
 * `background-image` fallback: that produced a real 404 on a live tip
 * widget, almost certainly Streamlabs' own CSS setting one on this id for
 * something unrelated to the donation image, picked up as if it were one.
 */
function readAvatar(): string | undefined {
  const el = document.getElementById("alert-image");
  if (!el) {
    return undefined;
  }
  const img = el instanceof HTMLImageElement ? el : el.querySelector("img");
  if (img) {
    const src = img.getAttribute("src");
    if (src && !isStreamlabsOwnMarkup(src)) {
      return img.src;
    }
  }
  const text = cleanText(el.textContent);
  return text && !isStreamlabsOwnMarkup(text) ? text : undefined;
}

function parseAmount(raw: string): number {
  const n = parseFloat(raw.replace(/[^0-9.]/g, ""));
  return isNaN(n) ? 0 : n;
}

function buildEvent(
  tokens: Element,
  boxType: StreamlabsAlertBoxType,
  tier: AlertTier,
): AlertStageEvent {
  const name = readName(tokens) || "someone";
  const avatar = readAvatar();
  const message =
    readRichText("alert-user-message") ||
    readToken(tokens, "message") ||
    undefined;
  // Streamlabs only fills this in when the streamer has set a custom
  // "Message Template" for this alert type in their own dashboard (unset
  // otherwise); when set, it's meant to replace the default one-liner
  // below it, that's the whole point of the streamer configuring it.
  const messageTemplate = readRichText("alert-message") || undefined;

  if (boxType === "follow") {
    return {
      type: "follow",
      name,
      avatar,
      detail: messageTemplate || "just followed",
      tier,
    };
  }
  if (boxType === "sub") {
    return {
      type: "sub",
      name,
      avatar,
      message,
      detail: messageTemplate || "1 month",
      amount: "1",
      tier,
    };
  }
  if (boxType === "resub") {
    const rawMonths = readToken(tokens, "months");
    const months = parseAmount(rawMonths) || 1;
    return {
      type: "sub",
      name,
      avatar,
      message,
      headline: "Resub",
      detail:
        messageTemplate || `${months} ${months === 1 ? "month" : "months"}`,
      amount: String(months),
      tier,
    };
  }
  if (boxType === "giftsub") {
    // {gifter} is the one paying, {name} is who receives it (only present
    // for a single-recipient gift), {amount} is the count (only present for
    // a community gift): confirmed from Streamlabs' own default templates,
    // "{gifter} has gifted a sub to {name}" vs.
    // "{gifter} has gifted {amount} subs to viewers!". An absent {gifter}
    // means an anonymous gift, either kind.
    const gifter = readToken(tokens, "gifter");
    const recipient = readToken(tokens, "name");
    const isAnonymous = !gifter;
    const count = parseAmount(readToken(tokens, "amount")) || 1;
    const isCommunity = count > 1 || !recipient;
    return {
      type: "sub",
      name: isAnonymous ? "An anonymous gifter" : gifter,
      avatar: isAnonymous ? undefined : avatar,
      message,
      headline: isCommunity ? "Community gift" : "Gifted sub",
      detail:
        messageTemplate ||
        (isCommunity
          ? `${count} subs gifted to the community`
          : `gifted a sub to ${recipient || "someone"}`),
      amount: isCommunity ? `×${count}` : undefined,
      tier,
      // A gifted sub is a distinct enough moment to earn its own accent, a
      // deeper shade of sub's magenta rather than regular subs' brighter
      // one: the four brand tones are all already claimed by other types.
      tone: "--magenta-contrast",
    };
  }
  if (boxType === "bits") {
    const amount = parseAmount(readToken(tokens, "amount"));
    return {
      type: "bits",
      name,
      avatar,
      message,
      amount: `${fmt(amount)} bits`,
      detail: messageTemplate || "cheered",
      tier,
    };
  }
  if (boxType === "raid") {
    const party = parseAmount(readToken(tokens, "count")) || 1;
    return {
      type: "raid",
      name,
      avatar,
      message,
      party,
      detail:
        messageTemplate ||
        `${party} ${party === 1 ? "mate in tow" : "mates in tow"}`,
      amount: String(party),
      headline: "Incoming raid",
      tier,
    };
  }
  // Streamlabs sends this already formatted for the donation's actual
  // currency (e.g. "A$97", not "$97"), so it's shown as-is rather than
  // reparsed into a bare number and given our own generic "$" prefix,
  // which silently dropped the streamer's real currency symbol.
  const amount = readToken(tokens, "amount");
  return {
    type: "tip",
    name,
    avatar,
    message,
    amount: amount || undefined,
    // Parsed separately from the displayed amount above: that one stays as
    // Streamlabs sent it (currency symbol included), this just needs a bare
    // number to scale the jar's fill against.
    fill: Math.min(1, parseAmount(amount) / TIP_HUGE_THRESHOLD),
    detail: messageTemplate || "chucked in",
    tier,
  };
}

const AVATAR_LOOKUP_URL =
  "https://zw-twitch-relay.djzwackery.workers.dev/twitch/avatar";

const AVATAR_FETCH_TIMEOUT_MS = 1200;

// Replace with the real token before pasting this into Streamlabs (ask
// whoever deployed the Worker for it, see worker/README.md). This file
// itself, including this literal placeholder, is served publicly from
// djzwackery.com, so the real token can never live here in source, only
// in the copy that actually gets pasted into your Streamlabs dashboard.
const API_TOKEN = "PASTE_YOUR_API_TOKEN_HERE";

/**
 * The relay Worker's `/twitch/avatar` response shape.
 */
interface AvatarLookupResponse {
  /**
   * The resolved avatar URL, or null if the login wasn't found or has no image.
   */
  avatarUrl: string | null;
}

/**
 * Best-effort live lookup for a real Twitch avatar via the relay Worker,
 * since Streamlabs' Alert Box gives no reliable avatar token itself. Uses
 * the resolved display name as the Twitch login, which only matches when
 * the two are identical, not guaranteed for a non-ASCII display name. Any
 * failure, including the timeout below, falls back to `undefined`, same as
 * an unresolved token, showing the placeholder glyph instead.
 */
async function fetchTwitchAvatar(login: string): Promise<string | undefined> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), AVATAR_FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(
      `${AVATAR_LOOKUP_URL}?login=${encodeURIComponent(login)}`,
      {
        signal: controller.signal,
        headers: { Authorization: `Bearer ${API_TOKEN}` },
      },
    );
    if (!res.ok) {
      return undefined;
    }
    const data = (await res.json()) as AvatarLookupResponse;
    return data.avatarUrl ?? undefined;
  } catch {
    return undefined;
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * On-screen `key: value` readout, opt in per widget via `data-debug="1"` on
 * `#zw-tokens` (control.html's Streamlabs section has a checkbox for it).
 * Exists because whoever pastes this into Streamlabs can't open devtools to
 * read a console log, so anything worth diagnosing has to be visible in a
 * screenshot instead.
 */
function renderDebugOverlay(info: Record<string, string>): void {
  const box = document.createElement("div");
  box.id = "zw-debug";
  box.style.cssText = [
    "position:fixed",
    "left:8px",
    "bottom:8px",
    "z-index:99999",
    "background:rgba(0,0,0,.85)",
    "color:#3f3",
    "font:11px/1.5 ui-monospace,monospace",
    "padding:8px 10px",
    "max-width:600px",
    "white-space:pre-wrap",
    "word-break:break-word",
    "pointer-events:none",
  ].join(";");
  box.textContent = Object.entries(info)
    .map(([k, v]) => `${k}: ${v || "(empty)"}`)
    .join("\n");
  document.body.appendChild(box);
}

const MAX_WAIT_MS = 3000;
const POLL_INTERVAL_MS = 100;
const MESSAGE_STABILIZE_MS = 500;

/**
 * Streamlabs doesn't necessarily substitute a token once and leave it: a
 * debug-overlay screenshot on a real widget showed a tip's `{amount}`
 * settle from an interim `$A$97` to a final `A$97`, the same kind of
 * staged self-correction `#alert-message` does while it wraps each
 * interpolated token in its own `<span>` for a letter-reveal animation.
 * `render()`'s own ready-check only waits for these to become non-empty,
 * not for them to stop changing, so `buildEvent()` could still read a
 * transient value. Waits, polling every `POLL_INTERVAL_MS`, until two
 * consecutive reads of everything `buildEvent()` touches match (stopped
 * changing) or `MESSAGE_STABILIZE_MS` runs out, whichever comes first: a
 * token that was never touched at all (nothing to correct) exits on the
 * very first check, since it never changes.
 */
async function waitForTokensToStabilize(tokens: Element): Promise<void> {
  const read = () =>
    ["name", "gifter", "count", "months", "amount", "message"]
      .map((t) => readToken(tokens, t))
      .concat([
        readAvatar() ?? "",
        readRichText("alert-user-message"),
        readRichText("alert-message"),
      ])
      .join("|");
  let last = read();
  const deadline = Date.now() + MESSAGE_STABILIZE_MS;
  while (Date.now() < deadline) {
    await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
    const current = read();
    if (current === last) {
      return;
    }
    last = current;
  }
}

/**
 * The second token (besides `{name}`) each type's display actually depends
 * on, so `render()` knows to wait for it too. giftsub has no single such
 * token, its ready-check is special-cased in `render()` instead.
 */
const NUMERIC_TOKEN: Partial<Record<StreamlabsAlertBoxType, string>> = {
  resub: "months",
  bits: "amount",
  raid: "count",
  tip: "amount",
};

/**
 * Streamlabs doesn't guarantee its tokens are already substituted into the
 * DOM the instant this script runs, only that they eventually are, so this
 * polls for up to `MAX_WAIT_MS`, well short of the alert's own 5s duration,
 * instead of a single read that could catch `{name}` or `NUMERIC_TOKEN` too
 * early and render with a default instead of the real value.
 */
async function render(startedAt = Date.now()): Promise<void> {
  const tokens = document.getElementById("zw-tokens");
  const boxType = tokens?.dataset.alertType as
    StreamlabsAlertBoxType | undefined;
  const root = document.getElementById("root");
  if (!tokens || !boxType || !root) {
    console.error(
      "[zw] streamlabs-alertbox.js: missing #zw-tokens[data-alert-type] or #root",
    );
    return;
  }
  const name = readName(tokens);
  // Only {name} was ever waited on, so a type whose display depends on a
  // second token (party size, months, amount...) could render before that
  // one had substituted, silently falling back to its own default. giftsub
  // has no single required token, gifter/name/amount are each legitimately
  // absent depending on condition (anonymous, community), so it's ready
  // once any one of the three has a value instead of requiring {name}.
  const numericToken = NUMERIC_TOKEN[boxType];
  const ready =
    boxType === "giftsub"
      ? ["gifter", "name", "amount"].some((t) => readToken(tokens, t) !== "")
      : name !== "" &&
        (!numericToken || readToken(tokens, numericToken) !== "");
  if (!ready && Date.now() - startedAt < MAX_WAIT_MS) {
    setTimeout(() => render(startedAt), POLL_INTERVAL_MS);
    return;
  }
  if (!ready) {
    console.warn(
      "[zw] streamlabs-alertbox.js: token(s) never resolved, using defaults",
      tokens.outerHTML,
    );
  }
  await waitForTokensToStabilize(tokens);
  const tier = (tokens.dataset.tier as AlertTier | undefined) || "big";
  const variant = tokens.dataset.variant || undefined;
  const event = buildEvent(tokens, boxType, tier);
  // event.name, not the outer `name`: for giftsub they diverge, the
  // standalone {name} token is the recipient, but event.name is whoever's
  // actually shown (the gifter, or "An anonymous gifter"). Looking up the
  // outer `name` there fetched the recipient's photo next to the gifter's
  // name, a real mismatch, and for an anonymous gift, leaked the
  // recipient's real avatar under an alert claiming anonymity.
  if (!event.avatar && event.name) {
    event.avatar = await fetchTwitchAvatar(event.name);
  }
  const durationSeconds = parseFloat(tokens.dataset.duration ?? "");
  const duration = isNaN(durationSeconds)
    ? DEFAULT_DURATION_MS
    : durationSeconds * 1000;
  const stage = new AlertStage(root, { top: TOP_OFFSET, onDone: () => {} });
  stage.show({ ...event, variant }, duration);

  if (tokens.dataset.debug === "1") {
    renderDebugOverlay({
      build: BUILD_MARKER,
      boxType,
      tier,
      "duration (ms)": String(duration),
      variant: variant || "(default)",
      "raw count": readToken(tokens, "count"),
      "raw months": readToken(tokens, "months"),
      "raw amount": readToken(tokens, "amount"),
      "raw gifter": readToken(tokens, "gifter"),
      "raw message": readToken(tokens, "message"),
      "raw userMessage": readRichText("alert-user-message"),
      "raw messageTemplate": readRichText("alert-message"),
      "raw alert-image markup":
        document.getElementById("alert-image")?.outerHTML ?? "",
      "event.name": event.name,
      "event.detail": event.detail ?? "",
      "event.message": event.message ?? "",
      "event.amount": event.amount ?? "",
      "event.fill": String(event.fill ?? ""),
      "event.party": String(event.party ?? ""),
      "event.avatar": event.avatar || "no (placeholder shown)",
    });
  }
}

void render();
